### PR TITLE
feat: leptos

### PR DESCRIPTION
**Pull request by cafkafk**
This was horrible to get working...

Currently it's a huge mess... requiring a lot of work...

...but integration tests pass...

9526-cool-finger-guns-crying

Signed-off-by: Christina Sørensen <christina@cafkafk.com>

### CODE REVIEW

**Comment by cafkafk** [comment]
If you wanna check it out, `cargo leptos watch`

**Comment by algernon** [comment]
It runs! Is the goal here to have a frontend too? Would it not make it easier if that was built as a different crate? (same repo, just another workspace)

What I'm saying is, we could split things into three parts: the backend, the frontend, and the CLI that can use either or both. And if all three were in separate workspaces, there wouldn't be much need for all those `cfg_if!{ ... }`s, no?

**Comment by cafkafk** [comment]
> What I'm saying is, we could split things into three parts: the backend, the frontend, and the CLI that can use either or both. And if all three were in separate workspaces, there wouldn't be much need for all those cfg_if!{ ... }s, no?

I mean, this would definitely be better, might take a while for me to get that working (with nix and containers and all that).

**Comment by algernon** [comment]
> > What I'm saying is, we could split things into three parts: the backend, the frontend, and the CLI that can use either or both. And if all three were in separate workspaces, there wouldn't be much need for all those cfg_if!{ ... }s, no?
> 
> I mean, this would definitely be better, might take a while for me to get that working (with nix and containers and all that).

It shouldn't need much massaging, I think. Cargo supports workspaces out of the box, and I suppose naersk has decent support for it too. Want me to have a go at it?

**Comment by cafkafk** [comment]
> It shouldn't need much massaging, I think. Cargo supports workspaces out of the box, and I suppose naersk has decent support for it too. Want me to have a go at it?

Heh, if you wanna I'm definitely not stopping you!

**Comment by cafkafk** [comment]
Now almost a year later, I think that what rime offers is semver, not a graphical discovery interface. As nice as having this could be, it should definitely be in a separate crate, and doing that would probably require a lot of rework, so I'm closing this for now since this will likely not be the PR to do it.

**Pull request closed without merging**
